import { CAPABILITY_KINDS, parseCapability } from '../../permissions/capabilities.ts';
import { MAX_SUBAGENT_DEPTH } from '../../subagents/types.ts';
import { DEFER_BELOW_TOKENS_SMALL } from '../context-budget.ts';
import { ERROR_CODES, type Tool, type ToolResult, toolError } from '../types.ts';
import { playbookDirsHint } from './task-shared.ts';

// `task_async` spawns a subagent without blocking the parent on its
// completion. Returns a handle the model can later pass to
// `task_await` (collect output) or `task_cancel` (preempt).
//
// Spec: ORCHESTRATION.md §3 (subagent spawn semantics) +
// CONTRACTS.md §2.6.4. Pairs with `task_sync`/`task` for the
// synchronous case.

export interface TaskAsyncInput {
  // Name of the subagent to spawn. Same resolution as `task`:
  // matched against the harness-level registry, kebab-case,
  // project scope shadowing user scope.
  subagent: string;
  // Initial user prompt for the child run. The child sees only
  // this — no parent history is leaked. Same 32 KiB cap as
  // `task`.
  prompt: string;
  // Capability list the child needs (PERMISSION_ENGINE.md §10.1).
  // REQUIRED — slice 94 closed the pre-slice gap where `task_async`
  // had ZERO §10 wiring (privilege escalation by omission).
  // Engine intersects declared ∩ parent and refuses spawn if any
  // declared capability is outside the parent's set. Pass [] for
  // pure-LLM subagent.
  capabilities: string[];
}

export interface TaskAsyncOutput {
  // Opaque handle the model passes to `task_await` /
  // `task_cancel`. Generated by the harness; clients should
  // treat as a string.
  handle_id: string;
  // The subagent's declared name, echoed back so the model's
  // planning text can refer to a specific spawn ("waiting on
  // the explore handle") without re-deriving from prompt.
  name: string;
  // Wall-clock at spawn time, ms epoch. Stable for the run —
  // any later `task_await` on the same handle reads the same
  // value.
  spawned_at: number;
}

// Same cap as `task`. Applied here too because the prompt still
// crosses the parent→child boundary as-is and is the dominant
// token cost a misbehaving caller could leak.
const PROMPT_MAX_BYTES = 32 * 1024;

export const taskAsyncTool: Tool<TaskAsyncInput, TaskAsyncOutput> = {
  name: 'task_async',
  description:
    'Spawn a named subagent without blocking on its completion. Returns a handle you can pass to `task_await` to collect the output later, or to `task_cancel` to abort. Use when you want to run multiple subagents in parallel — emit several `task_async` calls, then `task_await` each. Up to `max_concurrent_subagents` (default 3) run concurrently; the rest queue. The `prompt` must be self-contained.',
  inputSchema: {
    type: 'object',
    properties: {
      subagent: {
        type: 'string',
        description:
          'Name of the subagent to spawn. Must be kebab-case and match a discoverable definition.',
      },
      prompt: {
        type: 'string',
        description:
          'Self-contained user prompt for the child. Include all context the subagent needs — it has no view of this conversation.',
      },
      capabilities: {
        type: 'array',
        items: { type: 'string' },
        description: `Capabilities the child needs (PERMISSION_ENGINE.md §10.1), REQUIRED. Each entry is "kind" or "kind:scope"; kind ∈ [${CAPABILITY_KINDS.join(', ')}]. Only env-mutate, forja-mutate and host-passthrough are scope-less — every other kind REQUIRES a scope (read-fs:<path>, write-fs:<path>, delete-fs:<path>, exec:<shell|python|node|arbitrary>, net-egress:<host>, net-ingress:<port>, secret-access:<store>, git-write:<repo>). For a directory and everything under it the path MUST end in /** (e.g. read-fs:src/** or read-fs:/abs/repo/**); a bare read-fs:/abs/repo matches ONLY that path and covers NO files inside it — the #1 cause of a child denied on every read. The engine intersects declared ∩ parent and refuses the spawn if any capability is outside the parent's set. Pass [] for a pure-LLM child (no side-effect capabilities).`,
      },
    },
    required: ['subagent', 'prompt', 'capabilities'],
  },
  metadata: {
    category: 'misc',
    // Window-relative deferral (CONTEXT_TUNING §2.2): off the base surface on a
    // small window; reachable via tool_search.
    deferBelowTokens: DEFER_BELOW_TOKENS_SMALL,
    writes: false,
    idempotent: false,
    display: 'raw',
  },
  async execute(args, ctx): Promise<ToolResult<TaskAsyncOutput>> {
    if (ctx.signal.aborted) {
      return toolError(ERROR_CODES.aborted, 'tool aborted before spawning subagent', {
        retryable: true,
      });
    }
    if (ctx.subagentHandleStore === undefined) {
      // The harness was constructed without the async surface
      // (no subagent registry, or test wiring stopped before the
      // store). Same shape as `task`'s `subagent.unavailable`.
      return toolError(
        'subagent.unavailable',
        'subagents are not available in this run (no registry wired)',
        {
          hint: `The harness was built without subagentRegistry. Define agents under ${playbookDirsHint()} and bootstrap will pick them up.`,
        },
      );
    }
    if (typeof args.subagent !== 'string' || args.subagent.length === 0) {
      return toolError(ERROR_CODES.invalidArg, "'subagent' must be a non-empty string");
    }
    if (typeof args.prompt !== 'string' || args.prompt.length === 0) {
      return toolError(ERROR_CODES.invalidArg, "'prompt' must be a non-empty string");
    }
    // Depth pre-check at the tool surface. The dispatcher
    // (`spawnSubagentImpl` in the harness) also checks at await
    // time, but flushing here saves the round trip for a model
    // that called `task_async` at the cap: the legacy `task`
    // tool returns `subagent.depth_exceeded` before the spawn
    // happens; `task_async` should match that contract instead
    // of returning a handle whose later `task_await` is
    // pre-destined to fail.
    const childDepth = (ctx.subagentDepth ?? 0) + 1;
    if (childDepth > MAX_SUBAGENT_DEPTH) {
      ctx.recordGateDecision?.({
        decisionType: 'depth_exceeded',
        toolName: 'task_async',
        requestedName: args.subagent,
        details: { depth: childDepth, max_depth: MAX_SUBAGENT_DEPTH },
      });
      return toolError(
        'subagent.depth_exceeded',
        `subagent '${args.subagent}' would nest at depth ${childDepth} (max ${MAX_SUBAGENT_DEPTH})`,
        {
          hint: 'Stop nesting task() calls. Either finish the work directly in this turn or restructure into a flatter chain.',
          details: { depth: childDepth, max_depth: MAX_SUBAGENT_DEPTH },
        },
      );
    }
    const promptBytes = Buffer.byteLength(args.prompt, 'utf8');
    if (promptBytes > PROMPT_MAX_BYTES) {
      return toolError(
        ERROR_CODES.invalidArg,
        `'prompt' exceeds ${PROMPT_MAX_BYTES} bytes (got ${promptBytes})`,
        {
          hint: 'Subagent prompts should be self-contained instructions, not entire transcripts. Trim to the essentials.',
          details: { byte_limit: PROMPT_MAX_BYTES, byte_count: promptBytes },
        },
      );
    }

    // PERMISSION_ENGINE.md §10.1: capabilities REQUIRED (slice 94).
    // Pre-slice `task_async` had ZERO §10 wiring — async spawn was a
    // complete bypass of subagent inheritance. The review identified
    // this as the second leg of privilege-escalation-by-omission
    // alongside `task`'s opt-in. Same validation as `task` here
    // (intentional duplication; lifting to a shared helper deferred to
    // keep slice 94 surgical).
    if (args.capabilities === undefined) {
      return toolError(
        ERROR_CODES.invalidArg,
        "'capabilities' is required (PERMISSION_ENGINE.md §10.1)",
        {
          hint: "Declare the capabilities the child needs (e.g. ['read-fs:src/**', 'exec:shell']) or pass [] for a pure-LLM subagent with no side-effect capabilities.",
        },
      );
    }
    if (!Array.isArray(args.capabilities)) {
      return toolError(
        ERROR_CODES.invalidArg,
        "'capabilities' must be an array of capability strings",
      );
    }
    for (const entry of args.capabilities) {
      if (typeof entry !== 'string') {
        return toolError(
          ERROR_CODES.invalidArg,
          "'capabilities' entries must be capability strings (e.g. 'read-fs:src/**')",
        );
      }
      try {
        parseCapability(entry);
      } catch (e) {
        return toolError(
          ERROR_CODES.invalidArg,
          `'capabilities' entry '${entry}' is not a valid capability: ${(e as Error).message}`,
        );
      }
    }
    const declaredCapabilities: string[] = args.capabilities;
    // Resolve subagent name BEFORE issuing a handle. The estimate
    // getter returns `null` when the name doesn't match any
    // registered definition; coalescing that to 0 (the previous
    // behavior) let the spawn proceed and only failed at
    // `task_await`, regressing the sync `task` tool's
    // fail-fast-on-typo contract and burning a turn for every
    // invalid name. Distinct from `undefined` (the getter not
    // wired in test contexts) — that path falls back to the
    // legacy "no validation" behavior so headless/test
    // fixtures aren't broken.
    const estimateRaw = ctx.getSubagentBudgetEstimate?.(args.subagent);
    if (estimateRaw === null) {
      const available = ctx.getKnownSubagentNames?.() ?? [];
      ctx.recordGateDecision?.({
        decisionType: 'unknown_subagent',
        toolName: 'task_async',
        requestedName: args.subagent,
        details: { available },
      });
      return toolError('subagent.unknown', `subagent '${args.subagent}' not found`, {
        hint:
          available.length > 0
            ? `Known subagents: ${available.join(', ')}.`
            : `No subagents are defined. Add a .md file under ${playbookDirsHint()}.`,
        details: { available },
      });
    }
    const estimate = estimateRaw ?? 0;
    // Pre-spawn cost budget check (spec ORCHESTRATION.md §3.5).
    // Computes a projected total assuming this spawn lands at
    // its worst-case cost. Pessimistic reservation: every
    // in-flight handle's `definition.budget.maxCostUsd` already
    // counts via `getCostBudget().spent`, plus the new
    // estimate added here. If the total would exceed the cap,
    // refuse with `subagent.budget_exhausted` and let the model
    // fall back to settled-handle inspection or a smaller
    // spawn. The pessimistic reservation deviates from the
    // spec's strict "não pre-aloca" reading — the deviation is
    // documented as a deliberate safety choice, since without
    // mid-run cost-progress IPC the parent has no way to
    // observe in-flight spend.
    const budget = ctx.getCostBudget?.();
    if (budget !== undefined && budget.cap !== undefined && Number.isFinite(budget.cap)) {
      const projected = budget.spent + estimate;
      if (projected > budget.cap) {
        ctx.recordGateDecision?.({
          decisionType: 'budget_exhausted',
          toolName: 'task_async',
          requestedName: args.subagent,
          details: {
            spent: budget.spent,
            estimate,
            projected,
            cap: budget.cap,
          },
        });
        return toolError(
          'subagent.budget_exhausted',
          `spawning '${args.subagent}' would push projected cost to $${projected.toFixed(6)} (cap $${budget.cap.toFixed(6)})`,
          {
            retryable: false,
            hint: 'Wait for in-flight subagents to settle (their actual cost is usually less than the worst-case reservation) and retry, or cancel one via task_cancel to free its reservation, or finish the work without a new subagent.',
            details: {
              spent: budget.spent,
              estimate,
              projected,
              cap: budget.cap,
            },
          },
        );
      }
    }

    // Spawn returns immediately. The store's slot semaphore may
    // queue the underlying `runSubagent` call until a slot frees,
    // but the handle is created synchronously — the model can
    // confidently emit several task_async calls in one turn and
    // get a handle back for each.
    //
    // The wrap catches a synchronous throw from `store.spawn`.
    // Production stores persist the handle row at the top of
    // spawn(), and a failure there (FK violation: the parent
    // session row was dropped mid-run; CHECK constraint surface
    // in a future schema change; corrupted DB file) would
    // propagate as a JS exception. We surface it as a tool
    // error so the model sees a recoverable signal instead of
    // an uncaught throw escaping into the harness loop.
    let handle: ReturnType<typeof ctx.subagentHandleStore.spawn>;
    try {
      handle = ctx.subagentHandleStore.spawn(
        {
          name: args.subagent,
          prompt: args.prompt,
          // Slice 94 §10 wiring: declaredCapabilities now threads
          // through the store down to spawnSubagentImpl, which
          // runs intersectCapabilities against parent. If declared
          // is not ⊆ parent, the subsequent task_await/await-side
          // settles with subagent_escalation. The handle still gets
          // issued here so the model has a token to await on —
          // refusal surfaces at await time, NOT at handle time.
          declaredCapabilities,
        },
        // Forward the estimate so the store can include it in
        // `getReservedChildCostUsd()` for the duration of the
        // spawn. Pass 0 when no estimate is available — the
        // store's reservation tracker treats 0 as "no
        // reservation" and the load-bearing gate is in
        // `spawnSubagentImpl` (which can read the definition
        // directly), so this branch only loses the early-UX
        // refusal, not the safety net.
        { estimateCostUsd: estimate > 0 ? estimate : 0 },
      );
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      return toolError('subagent.spawn_failed', `failed to issue handle: ${message}`, {
        retryable: false,
        hint: 'The handle store rejected the spawn — most likely the parent session row was deleted or the database is unhealthy.',
      });
    }
    return {
      handle_id: handle.id,
      name: handle.name,
      spawned_at: handle.spawnedAt,
    };
  },
};
