export const migration016MemoryEvents = {
  id: 16,
  name: '016-memory-events',
  // Memory subsystem audit table.
  //
  // Spec MEMORY.md §5.3 mandates a single audit log for every
  // memory operation: proposed, created, edited, deleted, read,
  // refused, promoted, demoted. Memory CONTENT lives in the
  // markdown file itself (auditable via filesystem + git);
  // memory EVENTS live here so operators can answer "when did
  // this memory get created? from which session? was it inferred
  // or explicit? has anyone read it recently?".
  //
  // Schema rationale:
  //
  // - id (TEXT PRIMARY KEY). UUID v4 generated by the repo. Not
  //   an integer auto-increment because audit rows can be
  //   inserted concurrently from background subagent writes,
  //   and UUIDs let us avoid the SQLite-level row-id contention
  //   on hot insertion paths.
  //
  // - scope (TEXT NOT NULL CHECK). Three values per spec §2:
  //   'user', 'project_local', 'project_shared'. Stored as TEXT
  //   under CHECK so an operator-driven INSERT (e.g. importing
  //   from a backup) is gated by the same vocabulary the repo
  //   uses.
  //
  // - action (TEXT NOT NULL CHECK). The eight verbs from spec
  //   §5.3 plus 'expired' (added now to avoid a follow-up
  //   migration when 5.6 lands the lifecycle pass that records
  //   automatic expiry-driven deletions). Adding it upfront is
  //   free — the repo helpers in 5.1 don't emit it yet, so the
  //   value is just reserved.
  //
  // - memory_name (TEXT NOT NULL). The frontmatter `name` field.
  //   Joined here so audit queries can filter by memory without
  //   walking the filesystem. We do NOT store the absolute path
  //   — a memory may be promoted/demoted across scopes during
  //   its lifetime, and the (scope, name) pair is the stable
  //   identity. Path-derived columns would drift on rename.
  //
  // - source (TEXT NOT NULL CHECK). Provenance of the event,
  //   mirroring the frontmatter field. For 'read' / 'deleted' /
  //   'refused' events the source is the source of the
  //   originating proposal (or 'user_explicit' when the operator
  //   directly invoked /memory delete).
  //
  // - session_id (TEXT, nullable, FK ON DELETE SET NULL). Links
  //   the event to the session that triggered it. Nullable
  //   because some events have no session (operator running
  //   `/memory list` outside any active session, lifecycle
  //   sweeper running standalone). SET NULL on session purge
  //   keeps the audit row alive — you can still answer "this
  //   memory was created by inferred write at this time" even
  //   after the session itself was rotated out.
  //
  // - cwd (TEXT, nullable). Working directory at the time of
  //   the event. Null when the action happened outside a session
  //   (no cwd anchor). Required for trust-boundary forensics:
  //   "this 'inferred created' came from a non-trusted cwd"
  //   (spec §7.2 mitigation 3).
  //
  // - created_at (INTEGER NOT NULL). Epoch ms, Date.now()-shaped.
  //
  // - details (TEXT, nullable). JSON-serialized blob with
  //   action-specific extras: source-content hash for inferred
  //   writes (§7.2 mitigation 3), refusal reason for 'refused',
  //   from/to scopes for 'promoted'/'demoted'. Stored as TEXT
  //   under the same convention as other repos (subagent_runs,
  //   subagent_outputs); the repo serializes on write and parses
  //   on read.
  //
  // Indexes:
  //
  // - (session_id) WHERE NOT NULL. The hot read pattern is
  //   "/memory audit for the current session" — a partial index
  //   on the non-null subset keeps the index small while
  //   covering the actual query.
  //
  // - (memory_name, created_at DESC). The other hot read is
  //   "show me everything that ever happened to memory X" for
  //   the lifecycle / trust UIs. Composite ordered by recency
  //   so the natural query (`SELECT ... WHERE memory_name = ?
  //   ORDER BY created_at DESC LIMIT N`) is index-scanned.
  sql: `
    CREATE TABLE memory_events (
      id          TEXT PRIMARY KEY,
      scope       TEXT NOT NULL
                  CHECK (scope IN ('user', 'project_local', 'project_shared')),
      action      TEXT NOT NULL
                  CHECK (action IN (
                    'proposed', 'created', 'edited', 'deleted',
                    'read', 'refused', 'promoted', 'demoted', 'expired'
                  )),
      memory_name TEXT NOT NULL,
      source      TEXT NOT NULL
                  CHECK (source IN ('user_explicit', 'inferred', 'imported')),
      session_id  TEXT REFERENCES sessions(id) ON DELETE SET NULL,
      cwd         TEXT,
      created_at  INTEGER NOT NULL,
      details     TEXT
    );

    CREATE INDEX idx_memory_events_session
      ON memory_events(session_id)
      WHERE session_id IS NOT NULL;

    CREATE INDEX idx_memory_events_name
      ON memory_events(memory_name, created_at DESC);
  `,
} as const;
