// context_pins — pinned context primitive per CONTEXT_TUNING.md §12.4.
//
// Pin is an explicit "this constraint survives compaction, is re-
// injected with the goal, and shows up in auto-rehydrate." Cap of
// 10 per session forces prioritization (§12.4.2); enforcement of
// the cap lives in the repo (CHECK can't count rows) — the column
// shape here is the persistence contract, not the only invariant.
//
// Schema rationale:
//
// - id (TEXT PRIMARY KEY). UUID v4 generated by the repo. Same
//   reasoning as memory_events / outcome_signals — concurrent
//   inserts from the slash command vs. model-proposed tool path
//   would race on row-id otherwise.
//
// - session_id (TEXT NOT NULL, FK ON DELETE CASCADE). A pin
//   without a session is meaningless — pins are per-session by
//   design (cross-session would violate the memory contract per
//   spec §12.4.1). CASCADE on session purge is the AUDIT.md §1
//   declared retention behavior ("cascade com sessions"). Contrast
//   with memory_events which uses SET NULL because audit rows
//   carry standalone value — pin rows do not.
//
// - text (TEXT NOT NULL, length ≤ 500). The constraint /
//   workflow / invariant / reminder content the user wants
//   re-injected literally. 500 char ceiling per §12.4.2 forces
//   pins to stay short — if it doesn't fit, it probably belongs
//   in a memory entry instead. DB-level CHECK as defense-in-depth
//   complementing the repo-level validation.
//
// - kind (TEXT NOT NULL CHECK). Four values per §12.4.1.
//   Stored as TEXT under CHECK so an operator-driven INSERT
//   (replay, import) is gated by the same vocabulary the repo
//   uses.
//
// - created_at (INTEGER NOT NULL). Epoch ms, Date.now()-shaped.
//
// - created_by (TEXT NOT NULL CHECK). Two values: 'user' (slash
//   command) and 'model_proposed_user_approved' (pin_context tool
//   went through modal confirmation, idêntico a memory writes).
//   Note: a model-proposed pin only persists AFTER the operator
//   confirms; there is no 'model_proposed' transient state.
//
// - expires_at (INTEGER, nullable). NULL = vive até o fim da
//   sessão (cascade pega no purge). Epoch ms when set —
//   getActivePinsBySession filters (expires_at IS NULL OR
//   expires_at > now).
//
// - source_step_id (TEXT, nullable). Step that originated the
//   model-proposed pin; NULL for slash-driven pins. Used by recap
//   forensics ("which step led to this pin?") and not constrained
//   by FK — step_id is a logical id within the session, not a
//   foreign key into a step table.
//
// Indexes:
//
// - (session_id). Primary read path: "all pins for this session"
//   on goal re-injection / auto-rehydrate / `/pin --list`. Full
//   table scan would dominate large audit DBs even with low pin
//   counts per session.
//
// - (session_id, expires_at). Composite for getActivePins —
//   filter session, then expires_at predicate. expires_at NULLs
//   sort first in SQLite (ASC) which is fine; the predicate is
//   `expires_at IS NULL OR expires_at > ?` and SQLite uses the
//   index for the session_id filter regardless.
//
// Cap of 10 (§12.4.2) is NOT a CHECK constraint — SQLite CHECK
// can't reference COUNT subqueries. Enforced in createPin via
// withImmediateTransaction: read count, refuse if ≥ 10, insert
// atomically. The cap is part of the public contract, not a
// migration detail.

export const migration045ContextPins = {
  id: 45,
  name: '045-context-pins',
  sql: `
    CREATE TABLE context_pins (
      id              TEXT PRIMARY KEY,
      session_id      TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      text            TEXT NOT NULL CHECK (length(text) <= 500),
      kind            TEXT NOT NULL
                        CHECK (kind IN ('constraint', 'workflow', 'invariant', 'reminder')),
      created_at      INTEGER NOT NULL,
      created_by      TEXT NOT NULL
                        CHECK (created_by IN ('user', 'model_proposed_user_approved')),
      expires_at      INTEGER,
      source_step_id  TEXT
    );

    CREATE INDEX idx_context_pins_session
      ON context_pins(session_id);

    CREATE INDEX idx_context_pins_session_active
      ON context_pins(session_id, expires_at);
  `,
} as const;
