// eviction_events — typed lifecycle transitions across the four
// substrates governed by EVICTION.md §2 (memory, policy, candidate,
// slot_item). Each row is one of:
//
//   - `outcome = 'applied'`           — a state actually changed
//   - `outcome = 'blocked_by_protection'` — gate refused the
//                                       transition (pin, cooldown,
//                                       min-quarantine TTL, etc.)
//   - `outcome = 'blocked_by_hook'`   — the Eviction hook chain
//                                       refused (1.2.b wiring)
//   - `outcome = 'trigger_fired_no_action'` — evidence gate
//                                       refused (trigger thrashing)
//
// Spec §10.1 declares the canonical schema in PT-BR; this migration
// adapts two shapes for Forja convention:
//
//   1. `id` is TEXT PRIMARY KEY (UUID generated by the repo), not
//      INTEGER AUTOINCREMENT. Matches the pattern in
//      memory_events (016), failure_events (041), outcome_signals
//      (042) — globally-unique ids survive cross-install DB copies
//      and tests that swap DBs mid-run without colliding on
//      auto-increment sequences. `parent_id` follows suit.
//
//   2. `session_id` uses `REFERENCES sessions(id) ON DELETE SET NULL`
//      (memory_events pattern) instead of NOT NULL. Eviction events
//      can fire outside any session — startup probes that detect
//      source removal, GC sweeps, hook-driven security purges. A
//      session purge MUST NOT cascade-delete its audit history;
//      forensics needs the eviction trail to outlive the session.
//
// Schema rationale (per-column):
//
// - `id` (TEXT PRIMARY KEY). UUID v4 from `crypto.randomUUID()`.
//   Repo generates when caller doesn't supply.
//
// - `parent_id` (TEXT, nullable). The eviction event that
//   originated this transition (the trigger detection or the
//   prior `trigger_fired_no_action` row). NULL for root events.
//   No FK constraint — `parent_id` can reference a row in a
//   different `substrate`/`object_id` chain (a cross-substrate
//   cascade), so a CHECK over a single column wouldn't enforce
//   anything load-bearing.
//
// - `substrate` (TEXT NOT NULL CHECK). Closed enum. Memory entry
//   (cross-session persistent), adaptation policy (cross-session
//   persistent), retrieval candidate (per-query ephemeral),
//   context slot item (per-turn ephemeral). Spec §2.
//
// - `object_id` (TEXT NOT NULL). Identifier inside the substrate's
//   own namespace: memory `name`, policy `id`, candidate `node_id`,
//   slot item ref. No FK across substrates — each owner controls
//   its own id space; the eviction trail just references.
//
// - `object_scope` (TEXT NOT NULL). The scope tag the substrate
//   itself uses: session, repo, user, language, global (per
//   FEEDBACK_ADAPTATION §6 hierarchy). Free TEXT because each
//   substrate's vocabulary differs slightly (memory scopes are
//   user/project_local/project_shared; policy uses the broader
//   hierarchy). Writer layer constrains per call site.
//
// - `from_state`, `to_state` (TEXT NOT NULL CHECK). Both gated to
//   the 7-state enum from EVICTION §3. The repo's
//   isLegalTransition validator is the load-bearing gate; CHECK is
//   defense-in-depth (a future caller that bypasses the repo's
//   helper still can't INSERT a typo state).
//
// - `trigger` (TEXT NOT NULL). The §5.1 trigger kind. Stored as
//   free TEXT, NOT CHECK-constrained — the 12-element vocabulary
//   in spec §5.1 will grow as substrates ship (compaction adds
//   `token_pressure`/`turn_threshold` per §9.3; future detectors
//   add more). Writer-layer const set keeps the value space tight
//   without an ALTER TABLE per addition.
//
// - `motivo` (TEXT NOT NULL CHECK). Closed 8-element enum from
//   spec §0.4 (`irrelevant, conflict, shift, low_roi, quota,
//   expired, user_purge, security`). Adding a new motivo = ALTER
//   TABLE, forcing an explicit PR. Same discipline failure_events
//   uses on `classe`.
//
// - `evidence_json` (TEXT NOT NULL). Per-motivo payload schema
//   from §6.1 (e.g. for `low_roi`: `{tokens, load_bearing_count,
//   ratio}`). Writer serializes; reader parses defensively.
//   Sensitivity per AUDIT.md §1 = medium → redact before persist
//   (the JSON may carry path / args details forwarded from the
//   trigger source).
//
// - `outcome` (TEXT NOT NULL CHECK). Four-value enum. The CHECK
//   covers `applied | blocked_by_protection | blocked_by_hook |
//   trigger_fired_no_action`. `blocked_by_hook` is the 1.2.b
//   wiring outcome — added now so the migration doesn't need a
//   follow-up ALTER when the hook lands.
//
// - `blocked_by` (TEXT, nullable). When `outcome` is one of the
//   `blocked_by_*` values, names the specific guard (`pinned`,
//   `cooldown`, `min_quarantine_ttl`, or the hook spec id).
//   Free TEXT — the guard vocabulary is owner-specific.
//
// - `actor` (TEXT NOT NULL CHECK). Closed 5-element enum
//   (`loop_cold | compaction | user | hook | startup_probe`). Who
//   fired the trigger that produced this event. Different from
//   `motivo` (the reason) — same row can carry e.g. `actor=user,
//   motivo=user_purge` or `actor=loop_cold, motivo=low_roi`.
//
// - `session_id` (TEXT, nullable, FK ON DELETE SET NULL). Same
//   semantics as memory_events: the session that observed the
//   transition, NULL when no session anchor (startup probe, GC).
//   SET NULL preserves forensics across session purges.
//
// - `dependents_json` (TEXT, nullable). Per §6.4 cascade detection:
//   when this eviction *could* affect other objects (policy
//   referencing memory, slot item derived from memory), list
//   their ids here so the loop frio re-evaluates each. NULL =
//   no detected dependents. Spec is explicit that cascade is
//   never automatic — this is informational.
//
// - `recorded_at` (INTEGER NOT NULL). Epoch ms, Date.now()-shaped.
//
// - `purge_at` (INTEGER, nullable). When `to_state = 'evicted'`,
//   the unix-ms timestamp at which retention window expires and
//   the row should transition to `purged`. NULL for any other
//   `to_state`. The partial index `idx_evict_purge` covers the
//   GC sweep ("which evicted rows are due for purge?").
//
// Indices (verbatim from spec §10.1 except for the snake_case
// rename `idx_evict_*` matching the local convention):
//
// - (substrate, object_id): primary forensic query — "what
//   happened to this object?"
// - (to_state, recorded_at): "what's currently in state X?" /
//   "show the most recent transitions to evicted"
// - (purge_at) WHERE NOT NULL: partial index for the GC sweep
//   that materializes the `evicted → purged` transition once
//   the retention window expires.

export const migration046EvictionEvents = {
  id: 46,
  name: '046-eviction-events',
  sql: `
    CREATE TABLE eviction_events (
      id              TEXT PRIMARY KEY,
      parent_id       TEXT,
      substrate       TEXT NOT NULL
                        CHECK (substrate IN ('memory','policy','candidate','slot_item')),
      object_id       TEXT NOT NULL,
      object_scope    TEXT NOT NULL,
      from_state      TEXT NOT NULL
                        CHECK (from_state IN (
                          'proposed','active','shadow','quarantined',
                          'invalidated','evicted','purged'
                        )),
      to_state        TEXT NOT NULL
                        CHECK (to_state IN (
                          'proposed','active','shadow','quarantined',
                          'invalidated','evicted','purged'
                        )),
      trigger         TEXT NOT NULL,
      motivo          TEXT NOT NULL
                        CHECK (motivo IN (
                          'irrelevant','conflict','shift','low_roi',
                          'quota','expired','user_purge','security'
                        )),
      evidence_json   TEXT NOT NULL,
      outcome         TEXT NOT NULL
                        CHECK (outcome IN (
                          'applied',
                          'blocked_by_protection',
                          'blocked_by_hook',
                          'trigger_fired_no_action'
                        )),
      blocked_by      TEXT,
      actor           TEXT NOT NULL
                        CHECK (actor IN (
                          'loop_cold','compaction','user','hook','startup_probe'
                        )),
      session_id      TEXT REFERENCES sessions(id) ON DELETE SET NULL,
      dependents_json TEXT,
      recorded_at     INTEGER NOT NULL,
      purge_at        INTEGER
    );

    CREATE INDEX idx_evict_obj
      ON eviction_events(substrate, object_id);

    CREATE INDEX idx_evict_state
      ON eviction_events(to_state, recorded_at);

    CREATE INDEX idx_evict_purge
      ON eviction_events(purge_at)
      WHERE purge_at IS NOT NULL;
  `,
} as const;
